# Generated by Django 3.1.2 on 2020-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
